base_model: microsoft/Phi-3-mini-4k-instruct

load_in_4bit: true

ddp_find_unused_parameters: true

chat_template: |
  {% for message in messages %}
    <|{{ message['role'] }}|>
    {{ message['content'] }}
    <|end|>
  {% endfor %}
  {% if add_generation_prompt %}
    <|assistant|>
  {% endif %}

datasets:
  - path: suryanagar_training.json  # Your converted dataset
    type: json
    field: messages

dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: ./outputs/out

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_modules: 'model.language_model.layers.[\d]+.(mlp|cross_attn|self_attn).(up|down|gate|q|k|v|o)_proj'

# wandb_project:
# wandb_entity:
# wandb_watch:
# wandb_name:
# wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: true
fp16:
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
logging_steps: 1
flash_attention: true
eager_attention:

warmup_ratio: 0.1
evals_per_epoch: 1
saves_per_epoch: 1
weight_decay: 0.0