base_model: microsoft/Phi-3-mini-4k-instruct
model_type: Phi3ForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true

load_in_8bit: false
load_in_4bit: true
strict: false

lora_fan_in_fan_out: false
data_seed: 49
seed: 49



chat_template: phi_3  # CHANGE THIS from tokenizer_default

datasets:
  - path: /content/drive/MyDrive/ftcourse/sample_data/auryn_qna_json_output.jsonl
    type: chat_template
    field_messages: messages
    message_property_mappings:
      role: role
      content: content

train_on_inputs: false

dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir: ./phi3_mini_4k_ayurn_qna_with_json
# hub_model_id: hamel/hc-mistral-alpaca

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: false
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_target_modules: 
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

# wandb_project: knowledge-ft-phi3
# wandb_entity: innowhyte

gradient_accumulation_steps: 4
micro_batch_size: 16
eval_batch_size: 16
num_epochs: 3 #3-2  -- to remove overfitting and invention(hallucination)
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 2.0e-4 #2.0e-5-1.5e-5  -- to make model to take smaller and more careful steps while training
max_grad_norm: 1.0
adam_beta2: 0.95
adam_epsilon: 0.00001
save_total_limit: 12

train_on_inputs: false
group_by_length: true
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 20
evals_per_epoch: 4
eval_table_size:
eval_table_max_new_tokens: 128
saves_per_epoch: 2
debug:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "<|end|>" # end of sentence
  unk_token: "<unk>"

save_safetensors: true
